### ISSUE TITLE
Error while starting a new server

### ISSUE THREAD

**Issue by linonetwo** [stevenleeg/twproxy#3]
Start it with `twproxy -u xxx -P xxx -d http://localhost:8011/ -b 0.0.0.0 -p 8012`
And tiddlywiki with `tiddlywiki sss --listen host=0.0.0.0 port=8011`

```
[2019-04-14 18:07:01] ERROR NoMethodError: undefined method `split' for nil:NilClass
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/handler/webrick.rb:99:in `block in service'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:501:in `block in each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:500:in `each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:500:in `each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/handler/webrick.rb:91:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
59.78.171.134 - - [14/Apr/2019:18:07:01 CST] "PUT /recipes/default/tiddlers/%24%3A%2FStoryList HTTP/1.1" 500 326
http://112.74.178.182:8012/ -> /recipes/default/tiddlers/%24%3A%2FStoryList
[2019-04-14 18:07:54] ERROR NoMethodError: undefined method `split' for nil:NilClass
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/handler/webrick.rb:99:in `block in service'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:501:in `block in each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:500:in `each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:500:in `each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/handler/webrick.rb:91:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
59.78.171.134 - - [14/Apr/2019:18:07:54 CST] "PUT /recipes/default/tiddlers/%24%3A%2FStoryList HTTP/1.1" 500 326
http://112.74.178.182:8012/ -> /recipes/default/tiddlers/%24%3A%2FStoryList
[2019-04-14 18:07:54] ERROR NoMethodError: undefined method `split' for nil:NilClass
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/handler/webrick.rb:99:in `block in service'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:501:in `block in each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:500:in `each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/utils.rb:500:in `each'
        /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/handler/webrick.rb:91:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
59.78.171.134 - - [14/Apr/2019:18:07:54 CST] "PUT /recipes/default/tiddlers/Draft%20of%20'New%20Tiddler' HTTP/1.1" 500 326
http://112.74.178.182:8012/ -> /recipes/default/tiddlers/Draft%20of%20'New%20Tiddler'
59.78.171.134 - - [14/Apr/2019:18:08:00 CST] "GET /recipes/default/tiddlers.json HTTP/1.1" 200 2
http://112.74.178.182:8012/ -> /recipes/default/tiddlers.json
```

**Comment by stevenleeg** [comment]
Should be solved as of #4 being merged.
